services:
  app1:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3001:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=admin
      - DB_NAME=webapp
      - JWT_SECRET=miclavesegura
    depends_on:
      db:
        condition: service_healthy

  app2:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3002:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=admin
      - DB_NAME=webapp
      - JWT_SECRET=miclavesegura
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: webapp
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-padmin"]
      timeout: 20s
      retries: 10
      interval: 5s
      start_period: 30s

  nginx:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2

volumes:
  dbdata:
